### ISSUE TITLE
Interactive examples

### ISSUE THREAD

**Issue by wfro** [stevekinney/your-first-lines-of-js#2]
I'm not sure if this was your plan (some of the language hints at that being the case), but making the examples interactive could be cool, a la [Eloquent JavaScript](http://eloquentjavascript.net/09_regexp.html#c_O53a6v4BM0).

Ideally you'd be able to see the rendered output below each example.  Obviously easier said than done, but I'd be willing to look into this if no plans exist yet.

**Comment by stevekinney** [comment]
They should be interactive. If they're not, let me know what browser.

**Comment by wfro** [comment]
D'oh.  Brain forgot I was reading from the readme on github and not the live site.
